### ISSUE TITLE
Nie działa po aktualizacji

### ISSUE THREAD

**Issue by djborek** [patrykkolodziej/Abzynt-Cheat#1]
Siema source nie działa po dzisiejszej aktualizacji csgo.

**Comment by patrykkolodziej** [comment]
> Siema source nie działa po dzisiejszej aktualizacji csgo.

Musisz zaaktualizować.

**Comment by djborek** [comment]
Ale co zaktualizować?

śr., 1 maj 2019, 22:42 użytkownik Kołek <notifications@github.com> napisał:

**Comment by patrykkolodziej** [comment]
Offsety https://github.com/patrykkolodziej/Abzynt-Cheat/blob/master/Abzynt/Abzynt/sdk/offsets/offsets.hpp
Oraz player structa https://github.com/patrykkolodziej/Abzynt-Cheat/blob/master/Abzynt/Abzynt/sdk/entities/player/player.hpp#L12

**Comment by djborek** [comment]
A skad mogę wziąć aktualny player struct?

czw., 2 maj 2019 o 12:15 Kołek <notifications@github.com> napisał(a):
